Fixed Sanitizer issue file EngineRouteResource,LegacyAppResource,Name…
SEMOSS/Monolith pull request #35
Opened 2024-08-05 14:57 UTC by bhkushwah

2024-08-05 15:34 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/LegacyAppResource.java
> +		if(propFileLoc == null && !WebUtility.inputSanitizer(databaseId).equals("NEWSEMOSSAPP")) {
why are we adding the santizier on the if statement here but not below on line 278 when its more important?

2024-08-05 15:34 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/NameServer.java
> +		String routeCookieName = WebUtility.inputSanitizer(Utility.getDIHelperProperty(Constants.MONOLITH_ROUTE));
this is not needed - we need to sanitize user inputs, not constants/values we load from DI Helper

2024-08-05 16:50 UTC, bhkushwah commented on src/prerna/semoss/web/services/local/LegacyAppResource.java
> +		if(propFileLoc == null && !WebUtility.inputSanitizer(databaseId).equals("NEWSEMOSSAPP")) {
Updated

2024-08-06 15:30 UTC, kunal0137 requested changes

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/LegacyAppResource.java
> +		if(propFileLoc == null && !WebUtility.inputSanitizer(databaseId).equals("NEWSEMOSSAPP")) {
what was updated?

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/LegacyAppResource.java
> +				+ DIR_SEPARATOR + SmssUtilities.getUniqueName(databaseName, databaseId)
you need to clean here

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/NameServer.java
> +			hashTable.put(sheetNames.get(i), PlaySheetRDFMapBasedEnum.getClassFromName(WebUtility.inputSanitizer(sheetNames.get(i))));
can we just clean sheetname instead if we need to? instead of doing this in the for loop

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/NameServer.java
> +						routeId = WebUtility.inputSanitizer(c.getValue());
sql sanitize this vs input santiizer - you may need to merge in the latest dev

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/NameServer.java
> +		jt.addPixel(WebUtility.inputSanitizer(expression));
remove this sanitize

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/NameServer.java
> +		String expression = WebUtility.inputSanitizer(request.getParameter("expression"));
remove this sanitization

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/ProjectResource.java
> +			IReactor reactor = project.getReactor(WebUtility.inputSanitizer(reactorName), null);
remove this sanitization

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/ProjectResource.java
> +				sql = WebUtility.inputSanitizer(WebUtility.inputSanitizer(IOUtils.toString(request.getReader())));
remove this sanitization

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/SessionResource.java
> +		String redirectUrl = WebUtility.inputSanitizer(request.getHeader("referer"));
remove this sanitization

2024-08-06 15:30 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/auth/EngineAuthorizationResource.java
> +		List<Map<String, String>> permission = WebUtility.inputSanitizer( new Gson().fromJson(form.getFirst("userpermissions"), List.class));
has this been tested?

2024-08-07 06:51 UTC, bhkushwah commented on src/prerna/semoss/web/services/local/LegacyAppResource.java
> +				+ DIR_SEPARATOR + SmssUtilities.getUniqueName(databaseName, databaseId)
<img width="1330" alt="image" src="https://github.com/user-attachments/assets/7687b94d-81b1-4f05-b816-3241d2f95af1">
https://github.com/SEMOSS/Monolith/pull/35/commits/0ced889dbf9731a29eb939630488f0474a74ea80
Previous commit

2024-08-07 06:51 UTC, bhkushwah commented on src/prerna/semoss/web/services/local/NameServer.java
> +			hashTable.put(sheetNames.get(i), PlaySheetRDFMapBasedEnum.getClassFromName(WebUtility.inputSanitizer(sheetNames.get(i))));
Update

2024-08-07 06:51 UTC, bhkushwah commented on src/prerna/semoss/web/services/local/ProjectResource.java
> +				sql = WebUtility.inputSanitizer(WebUtility.inputSanitizer(IOUtils.toString(request.getReader())));
Updated

2024-08-07 06:52 UTC, bhkushwah commented on src/prerna/semoss/web/services/local/auth/EngineAuthorizationResource.java
> +		List<Map<String, String>> permission = WebUtility.inputSanitizer( new Gson().fromJson(form.getFirst("userpermissions"), List.class));
Updated

2024-08-07 06:52 UTC, bhkushwah commented on src/prerna/semoss/web/services/local/SessionResource.java
> +		String redirectUrl = WebUtility.inputSanitizer(request.getHeader("referer"));
Updated

2024-08-07 16:24 UTC, kunal0137 commented on src/prerna/semoss/web/services/local/auth/EngineAuthorizationResource.java
> +		List<String> ids = gson.fromJson(WebUtility.inputSanitizer(form.getFirst("ids")), List.class);
this can be removed - only need to do it once

2024-08-07 16:26 UTC, kunal0137 approved these changes

2024-08-07 16:39 UTC, merged